a1 = str(input('Digite algo: '))
print('O tipo primitivo desse algo é ',type(a1))
print('Só tem espaços? ', a1.isspace())
print('É um numero? ', a1.isnumeric())
print('É alfabético? ', a1.isalpha())
print('É Alphanumerico entao', a1.isalnum())
print('Está em maiuscula?', a1.isupper())
print('Em minuscula talvez ', a1.islower())
print('Está capitalizada? ',a1.istitle())
